version: '3'

services:
  frontend: 
    build: ./frontend
    container_name: docker-learn-frontend
    command: serve -s build -l 3000 
    ports: 
      - "3000:3000"
    restart: unless-stopped


  api:
    build: ./api
    container_name: docker-learn-api
    command: npm run start
    restart: unless-stopped
    ports:
     - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://docker-learn.localhost
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: docker-learn-auth
    command: npm run start
    restart: unless-stopped
    ports:
     - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://docker-learn.localhost
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
  
  api_db: 
    image: mongo:latest
    container_name: docker-learn-api-db
    volumes: 
      - mongodb_api:/data/db

  auth_db: 
    image: mongo:latest
    container_name: docker-learn-auth-db
    volumes: 
      - mongodb_auth:/data/db


volumes:
  mongodb_api: 
  mongodb_auth: 
